//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("2.0.0.60")]
[assembly: AssemblyFileVersion("2.0.0.60")]
[assembly: CLSCompliant(true)]
[assembly: AssemblyCompany("Cassia Developers")]
[assembly: AssemblyProduct("Cassia: .NET Terminal Services Library")]
[assembly: AssemblyCopyright("Copyright © 2008 - 2009")]


